const datadiri = {
  blnlahir: (function blnlahirnya() {
    let nilai = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']
    let idx = (Math.random() * nilai.length) | 0
    return nilai[idx]
  })(),
  tgllahir: function tgllahirnya() {
    let nilai = [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
      '16',
      '17',
      '18',
      '19',
      '20',
      '21',
      '22',
      '23',
      '24',
      '25',
      '26',
      '27',
      '28',
    ]
    let idx = (Math.random() * nilai.length) | 0
    return nilai[idx]
  },

  thnlahir: function thnlahirnya() {
    let nilai = ['1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993']
    let idx = (Math.random() * nilai.length) | 0
    return nilai[idx]
  },
  NoHP: function nohpnya() {
    let nilai = [
      '838',
      '831',
      '832',
      '833',
      '812',
      '813',
      '821',
      '822',
      '852',
      '853',
      '823',
      '851',
      '811',
      '817',
      '818',
      '819',
      '859',
      '877',
      '878',
      '815',
      '816',
      '855',
      '856',
      '857',
      '858',
      '881',
      '882',
      '883',
      '884',
      '885',
      '886',
      '887',
      '888',
      '889',
    ]
    let idx = (Math.random() * nilai.length) | 0
    let norandom = Math.floor(100000000 + Math.random() * 900000000)
    return nilai[idx] + norandom
  },
  Nama: function namanya() {
    let nilai = [
      'Daftar namanya',
      'Aarushi',
      'Abagael',
      'Abagail',
      'Abbey',
      'Abbi',
      'Abbie',
      'Abby',
      'Abdulmalik',
      'Abeja',
      'Abercrombie',
      'Abeyta',
      'Abi',
      'Abia',
      'Abigail',
      'Abree',
      'Abrianna',
      'Abrielle',
      'Abromaitis',
      'Aby',
      'Acacia',
      'Ada',
      'Adalia',
      'Adaline',
      'Adalyn',
      'Adams',
      'Adda',
      'Addie',
      'Addilyn',
      'Addison',
      'Adel',
      'Adela',
      'Adelaide',
      'Adele',
      'Adelene',
      'Adelia',
      'Adelina',
      'Adeline',
      'Adelle',
      'Adelynn',
      'Adena',
      'Adi',
      'Adina',
      'Adora',
      'Adoree',
      'Adrea',
      'Adreanna',
      'Adria',
      'Adriana',
      'Adrianna',
      'Adrianne',
      'Adrien',
      'Adrienne',
      'Ady',
      'Aerona',
      'Agatha',
      'Aggie',
      'Aggy',
      'Agnes',
      'Agnesse',
      'Agnus',
      'Ahlers',
      'Aida',
      'Aidonidis',
      'Aila',
      'Ailee',
      'Aileen',
      'Ailis',
      'Ailsa',
      'Ailsun',
      'Aimee',
      'Aine',
      'Ainsleigh',
      'Ainsley',
      'Aisha',
      'Aisling',
      'Aislinn',
      'Aislynn',
      'Aitchison',
      'Akerley',
      'Akilah',
      'Alaina',
      'Alana',
      'Alane',
      'Alanis',
      'Alanna',
      'Alannah',
      'Alasia',
      'Alaska',
      'Alayah',
      'Alayna',
      'Alayne',
      'Alba',
      'Albany',
      'Alberta',
      'Zyana',
    ]
    let idx = (Math.random() * nilai.length) | 0
    let idx2 = (Math.random() * nilai.length) | 1
    return [nilai[idx], nilai[idx2]]
  },
}

const dataekpor = {
  blnlahir: datadiri.blnlahir,
  tgllahir: datadiri.tgllahir(),
  thnlahir: datadiri.thnlahir(),
  NoHP: '0' + datadiri.NoHP(),
  NoHP62: '+62' + datadiri.NoHP(),
  namadepan: datadiri.Nama()[0],
  namabelakang: datadiri.Nama()[1],
  namalengkap: datadiri.Nama()[0] + ' ' + datadiri.Nama()[1],
}
module.exports = dataekpor
